### ISSUE TITLE
Define standard set of permissions to use globally

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/utils#225]
Define a standard set of default file permissions on creation/update to use globally for all tools.

Ref: https://github.com/projectdiscovery/nuclei/issues/3979

**Comment by dogancanbakir** [comment]
@Mzack9999 What do you think of using the existing permissions in utils/permissions? See: https://github.com/projectdiscovery/utils/blob/main/permission/permission_file.go#L42

**Comment by dogancanbakir** [comment]
Alternatively, we could mandate the use of utility functions. For example, https://github.com/projectdiscovery/utils/blob/main/file/file.go#L562

**Comment by dogancanbakir** [comment]
%100. Working on it.
