### ISSUE TITLE
IsInternal(str string)

### ISSUE THREAD

**Issue by brenocss** [projectdiscovery/utils#5]
iputil => https://github.com/projectdiscovery/retryabledns/blob/410b6d31595f720ed5d2b8c35a5db9d2607aa71e/validate.go

**Comment by Mzack9999** [comment]
I recommend turning this into a global instance and initializing it within the `init()` function at the package level. Then all the funcs can be turned to exported global while maintaining the same logic.
Consider also implementing tests if not present already in the original repository.
