### ISSUE TITLE
Ampersand symbol issue in unsafe mode of url util function ParseURL() 

### ISSUE THREAD

**Issue by KGorbakon** [projectdiscovery/utils#515]
### Current Behavior
The ampersand symbol disappears if it was placed in the end of URL. `http://1.1.1.1/abc/start.xml?===&` transforms to `http://1.1.1.1/abc/start.xml?===` in unsafe mode of [ParseURL function](https://github.com/projectdiscovery/utils/blob/main/url/parsers.go). The same behavior is observed in safe mode, so there is no difference between two modes in such case.

### Expected Behavior
Ampersand in the end of URL should't be deleted during parsing in unsafe mode.

### Steps To Reproduce
Run this code:
```
    package main

    import (
	"fmt"

	urlutil "github.com/projectdiscovery/utils/url"
    )

    func main() {	
        URL := "http://1.1.1.1/abc/start.xml?===&"
	fmt.Println("URL:", URL)
	ParsedURL, _ := urlutil.ParseURL(URL, true)
	fmt.Println("ParsedURL:", ParsedURL)
    }
```
Output:
```
URL: http://1.1.1.1/abc/start.xml?===&
ParsedURL: http://1.1.1.1/abc/start.xml?===
```

### Environment
- OS: Windows 10
- Go: go1.22.3 windows/amd64
- github.com/projectdiscovery/utils: v0.2.8

This issue relates to[ another issue](https://github.com/projectdiscovery/nuclei/issues/5592)

**Comment by dogancanbakir** [comment]
Closing this, see the discussion https://github.com/orgs/projectdiscovery/discussions/5620#discussioncomment-10590747
