### ISSUE TITLE
"IsIP" and "IsIPv4" are not able to i identify short ip address as Valid Ip address 

### ISSUE THREAD

**Issue by menavneet** [projectdiscovery/utils#80]
For Example "35.1" is a valid ip address which equivalent to "35.0.0.1"  and this kind of IP can be found in DNS record TXT

following example can show how these kind of can be recognised by single tool like "ping" and "nmap"
-----
<img width="451" alt="Screenshot 2023-02-08 at 9 03 43 PM" src="https://user-images.githubusercontent.com/26039819/217576222-808538f3-390f-4094-91c1-ad362e179ad2.png">

**Comment by menavneet** [comment]
<img width="475" alt="Screenshot 2023-02-08 at 9 11 11 PM" src="https://user-images.githubusercontent.com/26039819/217577912-35325f71-4eb5-4927-9b6b-7b7d2a00e055.png">

**Comment by xm1k3** [comment]
Hi @menavneet , could I ask you about the use cases in which you would use this functionality of keeping the ip in short form?

**Comment by menavneet** [comment]
when i try fetch IP from DNS TXT record , i missed these kind of ip

**Comment by menavneet** [comment]
@xm1k3 mostly in "v=spf1 *" record  of DNS TXT record i encounter there short form IP
